version: '3'
services:
  app:
    container_name: questionsandanswers
    build: . 
    ports: 
      - 8080:8080
    restart: on-failure
    depends_on:
    - postgresdb
    networks:
    - test-network

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgresdb
    ports:
      - 5432:5432
    networks:
      - test-network

networks:
  test-network:
    driver: bridge